### ISSUE TITLE
feature: allow pointing to custom github names in scripts/lib image-name()

### ISSUE THREAD

**Issue by raisjnn** [toltec-dev/toltec#30] opened 2020-09-11 20:19 UTC
currently matteodelabre is hardcoded, preventing others from mirroring this repository (and having the github actions work). this should be configurable by user somehow (github secrets?)

**Comment by raisjn** [comment] 2020-09-12 15:48
Duplicate of #33

**Closed by raisjn** 2020-09-12 15:48 UTC
Labels: tooling
